/*
 * import org.junit.Test;
 * import static org.junit.Assert.*;
 */

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'jb643' at '03/11/15 11:11' with Gradle 2.6
 *
 * @author jb643, @date 03/11/15 11:11
 */

/*
public class LibraryTest {
  @Test public void testSomeLibraryMethod() {
      Library classUnderTest = new Library();
  assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
  }
}
*/
