/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jb643' at '03/11/15 11:11' with Gradle 2.6
 *
 * @author jb643, @date 03/11/15 11:11
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
